name: piku_flutter
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  web_socket_channel: ^3.0.1
  json_annotation: ^4.9.0
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  equatable: ^2.0.5
  riverpod: ^2.6.1
  synchronized: ^3.3.0+3
  intl: ^0.19.0
  flutter_chat_types: ^3.6.2
  stream_channel: ^2.1.2
  async: ^2.11.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  markdown_widget: ^2.3.2+6
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  pigeon: ^22.6.2


flutter:
  assets:
    - assets/

